### ISSUE TITLE
After i migrate to 2.26 ( from 1.x ) i cannot run converge anymore

### ISSUE THREAD

**Issue by EugenMayer** [higanworks/knife-zero#140]
running converge ends with

```
WARNING: Failed to connect to <REDACTED> -- ArgumentError: Expected -----END OPENSSH PRIVATE KEY-----
          at end of private key
ERROR: NoMethodErrorundefined method `forward' for nil:NilClass
ERROR: /home/em/.chefdk/gem/ruby/2.6.0/gems/knife-zero-2.2.1/lib/knife-zero/bootstrap_ssh.rb:35:in `block in ssh_command'
       /home/em/.chefdk/gem/ruby/2.6.0/gems/knife-zero-2.2.1/lib/knife-zero/bootstrap_ssh.rb:33:in `each'
       /home/em/.chefdk/gem/ruby/2.6.0/gems/knife-zero-2.2.1/lib/knife-zero/bootstrap_ssh.rb:33:in `ssh_command'
       /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.5.17/lib/chef/knife/ssh.rb:628:in `run'

```

Any hints on what changed? Checked the changelog, checked the readme and found https://github.com/higanworks/knife-zero/issues/13 - the latter i do not understand a word of it :)

If of any interest, i migrated from chef client 13 to 15 with this update

Thanks!

**Comment by sawanoboly** [comment]
How did you update? And please tell me what command line options you use.

The message is from net-ssh, is the file path of the private key correct?
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/ed25519.rb#L45

**Comment by EugenMayer** [comment]
@sawanoboly which part you are interested, the host or the client update?

On the client/node i just upgraded the client using the .deb package available ( for debian )..

On the client, i switched from MacOS to Linux so i basically installed from scratch. 

I use the chef-dk AUR package for arch https://aur.archlinux.org/packages/chef-dk and installed knife zero using `bundle updateb` and this modified gemfile

```
source 'https://rubygems.org'
# 2.x is not yet supported, we would need chef 15 for that, see https://github.com/higanworks/knife-zero/#200-or-later
gem 'knife-zero', '>=2.0'
```

I did not migrate/update anything else

**Comment by sawanoboly** [comment]
hmm... could you try to use RSA format private key instead openssh?

```
ssh-keygen -t rsa -f ~/.ssh/test
```

or, other format https://github.com/net-ssh/net-ssh/issues/478

**Comment by sawanoboly** [comment]
https://github.com/net-ssh/net-ssh/issues/731

Or, please try to remove extra newline from private key file.

**Comment by EugenMayer** [comment]
@sawanoboly your deeplink seems to no work - which comment do you mean?

**Comment by sawanoboly** [comment]
@EugenMayer 

> please try to remove extra newline from private key file.

↑.

**Comment by EugenMayer** [comment]
Seems to work now - sorry. Yet, while using this key quiet a bit, never expirienced this newline issue

**Comment by sawanoboly** [comment]
Don't worry about it. Probably a problem arising from 5.2.0 of net-ssh.

**Comment by sawanoboly** [comment]
FYI

I've created PR to net-ssh https://github.com/net-ssh/net-ssh/pull/736
